### PR TITLE
created a payment form structure

### PR DESCRIPTION
**Pull request by komenAnna**
### Description
Created a payment form structure from scratch to understand on HTML forms structural elements. 
Motivation was to understand a web form structure and a form structural elements such as fieldset, label and input etc

# Type of change
How to structure a web form

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Details

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Introduces a new feature -- a web form

- **What is the current behavior?** (You can also link to an open issue here)
It is static i.e has no functionality

## Screenshots (if applicable)
Payment Form Structure

## References
[Mozilla - How to structure a web form](https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gertie-sheshe** [comment]
Was I to review this? @komenAnna

**Comment by komenAnna** [comment]
Yes. It was on Project two.
The second form

**Comment by gertie-sheshe** [comment]
Oh, I did not see this. Could you please add all three project PRs and their links to the card - so I can know which is which @komenAnna

**Comment by komenAnna** [comment]
Yes, will do.

**Pull request merged**
